### ISSUE TITLE
No links on social media section

### ISSUE THREAD

**Issue by tessarin** [AlvaroCalsolari/AlvaroCalsolari.github.io#1]
I think the footer area reserved to social media is meant to have links, but currently there are none. They are just plain text list items. From [_index.html:173-175_][footer]

    <li><i class="fa fa-facebook-official" aria-hidden="true"></i>Facebook</li>
    <li><i class="fa fa-github" aria-hidden="true"></i>Github</li>
    <li><i class="fa fa-linkedin" aria-hidden="true"></i>Linkedin</li>

Will it be fixed soon?

Other than that, looking good!

 [footer]: https://github.com/AlvaroCalsolari/AlvaroCalsolari.github.io/blob/c7a8e93c23060172a49f2dfbe286d4426af84516/index.html#L173-L175

**Comment by AlvaroCalsolari** [comment]
# Thank you for the warning

In my last commit I added the respective social networking links as you can see <a href="https://alvarocalsolari.github.io/">here</a>.
**If there is anything else that is not working as it should, let me know .**

_This is a work in progress, so criticisms or suggestions are welcome XD._

**Comment by tessarin** [comment]
Thanks! Looks great. And since it was fixed with 1965192 I'll close this issue now.
